// Fetch
export const FETCH_POSTS_INIT = 'FETCH_POSTS_INIT'
export const FETCH_POSTS_COMPLETED = 'FETCH_POSTS_COMPLETED'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'

// Create
export const CREATE_POST_INIT = 'CREATE_POST_INIT'
export const CREATE_POST_COMPLETED = 'CREATE_POST_COMPLETED'
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR'

// Update
export const UPDATE_POST_INIT = 'UPDATE_POST_INIT'
export const UPDATE_POST_COMPLETED = 'UPDATE_POST_COMPLETED'
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR'

// Delete
export const REMOVE_POST_INIT = 'REMOVE_POST_INIT'
export const REMOVE_POST_COMPLETED = 'REMOVE_POST_COMPLETED'
export const REMOVE_POST_ERROR = 'REMOVE_POST_ERROR'

