// Fetch
export const FETCH_COMMENTS_INIT = 'FETCH_COMMENTS_INIT'
export const FETCH_COMMENTS_COMPLETED = 'FETCH_COMMENTS_COMPLETED'
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR'

// Create
export const CREATE_COMMENT_INIT = 'CREATE_COMMENT_INIT'
export const CREATE_COMMENT_COMPLETED = 'CREATE_COMMENT_COMPLETED'
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR'

// Update
export const UPDATE_COMMENT_INIT = 'UPDATE_COMMENT_INIT'
export const UPDATE_COMMENT_COMPLETED = 'UPDATE_COMMENT_COMPLETED'
export const UPDATE_COMMENT_ERROR = 'UPDATE_COMMENT_ERROR'

// Delete
export const REMOVE_COMMENT_INIT = 'REMOVE_COMMENT_INIT'
export const REMOVE_COMMENT_COMPLETED = 'REMOVE_COMMENT_COMPLETED'
export const REMOVE_COMMENT_ERROR = 'REMOVE_COMMENT_ERROR'

